### ISSUE TITLE
Undefined reference in Network_Ping_Sleep.ino Example

### ISSUE THREAD

**Issue by PRONOVATEK** [TMRh20/RF24Network#34]
hi, I received the following error message when compiling the example of node sleep on a Arduino UNO:

Arduino: 1.5.8 (Mac OS X), Placa:"Arduino Uno"

Network_Ping_Sleep.cpp.o: In function `setup':
/Network_Ping_Sleep.ino:104: undefined reference to `RF24Network::setup_watchdog(unsigned char)'
Network_Ping_Sleep.cpp.o: In function `loop':
/Network_Ping_Sleep.ino:139: undefined reference to `RF24Network::sleepNode(unsigned int, int)'
collect2: error: ld returned 1 exit status
compile error

I copy the library RF24Network.h on Contents/Java/libraries/RF24Nework-master folder into Arduino.app

unaware that marks this mistake in advance appreciate your advice on this error.

**Comment by lnxbil** [comment]
Only the header will not help. RF24Network should bring its own ```.h``` and ```.c``` files. I don't know it the Arduino IDE is picky, but you can rename it if ```RF24Network``` without the ```-master``` suffix , maybe that'll do it.

**Comment by TMRh20** [comment]
The RF24Network examples need a lot of work, this one in particular. I thought I had commented on this, but sleep mode needs to be enabled in the RF24Network_config.h file. I see the example still refers to and old method of slleeping I had been experimenting with too, so that needs to be cleaned up or removed as well. This may happen soon, since the DEV lib is now pretty stable and has been cleaned up a bit.
