### ISSUE TITLE
RF24Network Message Forwarding

### ISSUE THREAD

**Issue by Stephan1973** [TMRh20/RF24Network#51]
Hello,

fist let me say that i was excited about this class.
I build my own Home-Control app an everything works fine.

But, if i use Message forwarding and send data which like "10", "10123", "10111", an empty  message was received from the base node. 
The reason is the "10" at the beginning of the payload. If it starts with "20" "11" "1110" everything works fine.

Here is a part of my code (i used the default Radio settings):

Arduino:

    const uint16_t this_node = 011;
    const uint16_t parrent_node = 01; 

    callback = "10";
    Send the final one back.
    String strRespTemp = callback;
    char responseRF[32] = "";
    char charRespTemp[31];
    strRespTemp.toCharArray(charRespTemp, strRespTemp.length() + 1); 
    strcpy (responseRF, charRespTemp);
    RF24NetworkHeader header(parrent_node);
    bool ok = network.write(header,&responseRF,sizeof(responseRF));

Ras-Pi:

    const uint16_t this_node = 00;
    char receivePayload[32];

    RF24NetworkHeader header;
    network.read(header,&receivePayload,sizeof(receivePayload));

Thanks for helping, Stephan

**Comment by TMRh20** [comment]
Hi, I'm not sure exactly what the problem is, but I'm thinking it may have something to do with your code.

> But, if i use Message forwarding and send data which like "10", "10123", "10111", an empty message was received from the base node. 

Which node is sending, which is receiving, and what are the addresses involved?

I would also need to recreate the issue if it is related to the library... can you recreate the issue using the network_tx and rx examples?

[This](https://en.wikipedia.org/wiki/Wikipedia:Reference_desk/How_to_ask_a_software_question) is helpful also when trying to figure stuff like this out.
